name: Update Dependencies Safely

on:
  schedule:
    - cron: '0 0 * * 0' # roda todo domingo à meia-noite
  workflow_dispatch: # permite rodar manualmente

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Pull latest changes first
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "There are unstaged changes. Skipping pull."
          else
            git pull origin main
          fi

      - name: Update dependencies (back-end & front-end)
        run: |
          npm install --prefix back-end
          npm update --prefix back-end
          npm install --prefix front-end
          npm update --prefix front-end

      - name: Debug modified files
        run: git status

      - name: Commit and Push
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "chore: update dependencies"
            git push
          else
            echo "No changes to commit."
          fi
