- name: Commit and Push
if: github.ref == 'refs/heads/main'
run: |
  # Configure git
  git config --global user.name "GitHub Actions"
  git config --global user.email "actions@github.com"
  
  # Check if there are changes to commit
  if [ -n "$(git status --porcelain)" ]; then
    # Stage changes
    git add package.json package-lock.json
    
    # Commit changes
    git commit -m "chore(deps): safe dependency updates [skip ci]"
    
    # Pull latest changes with rebase
    git pull --rebase origin main
    
    # Push changes
    git push
  else
    echo "No changes to commit"
  fi
