name: Update Dependencies Safely

on:
  schedule:
    - cron: "0 3 * * *"  # Roda todo dia às 03:00 UTC
  workflow_dispatch:      # Permite rodar manualmente pelo GitHub

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Smart Dependency Updates
        run: |
          npx npm-check-updates \
            --target patch \
            --reject "express,path-to-regexp,vite" \
            --upgrade

          npm install --no-audit
          npm audit fix --dry-run || true

      - name: Debug modified files
        run: |
          git status
          git diff --name-only

      - name: Commit and Push
        if: github.ref == 'refs/heads/main'
        run: |
          # Configure git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Pull latest changes with rebase BEFORE modifying anything
          git pull --rebase origin main

          # Check if there are changes to commit
          if [ -n "$(git status --porcelain)" ]; then
            # Stage changes
            git add package.json package-lock.json

            # Commit changes
            git commit -m "chore(deps): safe dependency updates [skip ci]"

            # Push changes
            git push
          else
            echo "No changes to commit"

