name: Update Dependencies Safely
on:
  schedule:
    - cron: "0 3 * * *"  # 3AM UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Smart Dependency Updates
        run: |
          # Instala ferramenta melhorada
          npm install -g npm-check-updates
          
          # 1. Atualiza SOMENTE patches e minors (evita majors)
          ncu --target patch
          
          # 2. Ignora pacotes específicos problemáticos
          ncu --reject "express,path-to-regexp,vite"
          
          # 3. Verifica atualizações críticas de segurança
          npm audit fix --dry-run
          
          # 4. Aplica atualizações seguras
          npm install --package-lock-only --no-audit

      - name: Commit Changes
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Verifica mudanças reais antes de commitar
          git add package.json package-lock.json
          if ! git diff --cached --quiet; then
            git commit -m "chore(deps): safe dependency updates [skip ci]"
            git push
          else
            echo "Nenhuma atualização segura encontrada."
          fi